const MAX_SCREEN = 1280
const MEDIUM_SCREEN = 1250
const SMALL_SCREEN = 763
const AMOUNT_MORE_MAX_SCREEN = 12
const AMOUNT_LESS_MAX_SCREEN = 12 
const AMOUNT_MEDIUM_SCREEN = 8 
const AMOUNT_SMALL_SCREEN = 5
const STEP_MAX_SCREEN = 3
const STEP_MEDIUM_SCREEN = 3
const STEP_SMAL_SCREEN = 2

export {
MAX_SCREEN,
MEDIUM_SCREEN,
SMALL_SCREEN,
AMOUNT_MORE_MAX_SCREEN,
AMOUNT_LESS_MAX_SCREEN,
AMOUNT_MEDIUM_SCREEN,
AMOUNT_SMALL_SCREEN,
STEP_MAX_SCREEN,
STEP_MEDIUM_SCREEN,
STEP_SMAL_SCREEN,
}